spring:

  datasource:
    url: ${jdbc-url}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${admin}
    password: ${rds-pw}

#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id:
#            client-secret:
#          google:
#            client-id:
#            client-secret:


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
