spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${jdbc-url}
    username: ${username}
    password: ${password}

#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id:
#            client-secret:
#          google:
#            client-id:
#            client-secret:


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

