spring:
  redis:
    host: localhost
    port: 6379

  profiles:
    include:
      - jwt
      - oauth
      - fcm
    active: jwt, oauth, fcm
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${jdbc-url}
    username: ${username}
    password: ${password}

  config:
    name: application,application-jwt,application-oauth,application-fcm
    location: classpath:/application.yml,classpath:/application-jwt.yml,classpath:/application-oauth.yml,calsspath:/application-fcm.yml


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    show-sql: true