spring:
  profiles:
    group:
      "local": "local, jwt, oauth"
      active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${jdbc-url}
    username: ${username}
    password: ${password}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${github-id}
            client-secret: ${github-secret}
            redirectUri: "http://3.38.8.89:8080/login/oauth2/code/"
            scope: user
  #          google:
  #            client-id:
  #            client-secret:


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100