spring:
  profiles:
    include: oauth
  config:
    import:
      - classpath:/config/application.yml
      - classpath:/config/application-oauth.yml

  datasource:
    url: jdbc:mariadb://localhost:3306/mogakco_local
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
