spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
          google:
            client-id:
            client-secret:


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100