spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${github-id}
            client-secret: ${github-secret}
            redirectUri: ${github-callback}
            scope: user
    #          google:
    #            client-id:
    #            client-secret: